"""empty message

Revision ID: fc80c2915833
Revises: 9482cf4ce05f
Create Date: 2022-10-19 16:44:38.943730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc80c2915833'
down_revision = '9482cf4ce05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorite', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_column('favorite', 'user_id')
    # ### end Alembic commands ###
